### ISSUE TITLE
The problem of professional version Pycharm

### ISSUE THREAD

**Issue by Runsheng-Wang** [econ-innovation/Notification#1]
Applying for the professional version of PyCharm with an educational email, it prompts for the submission of the Academic Credentials Verification Code. Approximately, how long does this verification process take?
![WechatIMG955](https://github.com/econ-innovation/Notification/assets/133568500/857e1ad4-850e-4edf-b2c8-efea246f0eea)

**Comment by HengfeiMa95** [comment]
I just took a few seconds.

**Comment by Runsheng-Wang** [comment]
> I just took a few seconds.

I have waited for about one day and there is still no reply from the PyCharm.

**Comment by HengfeiMa95** [comment]
That’s weird may u need to prosess it again

---- Replied Message ----
From Runsheng ***@***.***> Date 12/12/2023 01:24 To econ-innovation/Notification ***@***.***> Cc HengfeiMa95 ***@***.***>,
Comment ***@***.***> Subject Re: [econ-innovation/Notification] The problem of professional version Pycharm (Issue #1)  

I just took a few seconds.
I have waited for about one day and there is still no reply from the PyCharm.

**Comment by Runsheng-Wang** [comment]
> That’s weird may u need to prosess it again
> […](#)
> ---- Replied Message ---- From Runsheng ***@***.***> Date 12/12/2023 01:24 To econ-innovation/Notification ***@***.***> Cc HengfeiMa95 ***@***.***>, Comment ***@***.***> Subject Re: [econ-innovation/Notification] The problem of professional version Pycharm (Issue #1) I just took a few seconds. I have waited for about one day and there is still no reply from the PyCharm. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I emailed the PyCharm, then got the reply that I will wait for 1 or 2 weeks....

**Comment by JiLisx** [comment]
It seems too complicated. Try this link and get free educational license immediately:

https://www.jetbrains.com/help/pycharm/pycharm-educational.html

**Comment by Runsheng-Wang** [comment]
> It seems too complicated. Try this link and get free educational license immediately:
> 
> https://www.jetbrains.com/help/pycharm/pycharm-educational.html

This way worked quickly!
